// Generated contract snapshot for the current API.
// Regenerate with `npm run api:generate` while the backend is running.

export interface paths {
  "/api/system/version": { get: { responses: { 200: { content: { "application/json": components["schemas"]["SystemVersionResponse"] } } } } };
  "/api/projects/": { get: { responses: { 200: { content: { "application/json": components["schemas"]["ProjectResponse"][] } } } }; post: { requestBody: { content: { "application/json": components["schemas"]["ProjectUpsertRequest"] } }; responses: { 201: { content: { "application/json": components["schemas"]["ProjectResponse"] } } } } };
  "/api/projects/{id}": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["ProjectResponse"] } }; 404: { content?: never } } }; put: { parameters: { path: { id: string } }; requestBody: { content: { "application/json": components["schemas"]["ProjectUpsertRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["ProjectResponse"] } }; 404: { content?: never } } }; delete: { parameters: { path: { id: string } }; responses: { 204: { content?: never }; 404: { content?: never } } } };
  "/api/projects/{id}/song": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["ProjectSongResponse"] } }; 404: { content?: never } } }; post: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["ProjectSongResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };
  "/api/projects/{projectId}/analysis/": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["SongAnalysisResponse"] } }; 404: { content?: never } } }; post: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["SongAnalysisResponse"] } }; 400: { content?: unknown }; 404: { content?: never }; 422: { content?: unknown } } } };
  "/api/projects/{projectId}/analysis/versions": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["SongAnalysisResponse"][] } } } } };
  "/api/projects/{projectId}/analysis/sections": { put: { parameters: { path: { projectId: string } }; requestBody: { content: { "application/json": components["schemas"]["SongSectionRequest"][] } }; responses: { 200: { content: { "application/json": components["schemas"]["SongAnalysisResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };
  "/api/projects/{projectId}/analysis/lyrics/timing": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["LyricTimingResponse"] } }; 404: { content?: never } } }; post: { parameters: { path: { projectId: string } }; requestBody: { content: { "application/json": components["schemas"]["TranscriptionSegmentRequest"][] } }; responses: { 200: { content: { "application/json": components["schemas"]["LyricTimingResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };
  "/api/projects/{projectId}/analysis/lyrics/timing/versions": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["LyricTimingResponse"][] } } } } };

  "/api/projects/{projectId}/director/plan": { post: { parameters: { path: { projectId: string } }; requestBody: { content: { "application/json": components["schemas"]["DirectorPlanRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["DirectorPlanResponse"] } }; 400: { content?: unknown }; 404: { content?: never }; 409: { content?: unknown }; 422: { content?: unknown }; 503: { content?: unknown } } } };
  "/api/projects/{projectId}/director/visual-arc": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["VisualArcResponse"] } }; 404: { content?: never } } }; put: { parameters: { path: { projectId: string } }; requestBody: { content: { "application/json": components["schemas"]["VisualArcUpdateRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["VisualArcResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };
  "/api/projects/{projectId}/director/visual-arc/versions": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["VisualArcResponse"][] } } } } };
  "/api/projects/{projectId}/director/storyboard": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["StoryboardResponse"] } }; 404: { content?: never } } } };
  "/api/projects/{projectId}/director/storyboard/versions": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["StoryboardResponse"][] } } } } };
  "/api/projects/{projectId}/director/storyboard/scenes/{sceneId}": { put: { parameters: { path: { projectId: string; sceneId: string } }; requestBody: { content: { "application/json": components["schemas"]["SceneUpdateRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["StoryboardResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };
  "/api/projects/{projectId}/director/storyboard/reorder": { post: { parameters: { path: { projectId: string } }; requestBody: { content: { "application/json": components["schemas"]["SceneReorderRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["StoryboardResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };
  "/api/projects/{projectId}/director/storyboard/scenes/{sceneId}/prompts": { get: { parameters: { path: { projectId: string; sceneId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["PromptVersionResponse"][] } } } } };
  "/api/projects/{projectId}/director/storyboard/scenes/{sceneId}/prompts/regenerate": { post: { parameters: { path: { projectId: string; sceneId: string } }; requestBody: { content: { "application/json": components["schemas"]["PromptRegenerateRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["PromptRegenerateResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };

  "/api/projects/{id}/export": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": unknown } }; 404: { content?: never } } } };
  "/api/projects/import": { post: { requestBody: { content: { "application/json": unknown } }; responses: { 201: { content: { "application/json": components["schemas"]["ProjectResponse"] } } } } };

  "/api/library/items": { get: { responses: { 200: { content: { "application/json": components["schemas"]["VisualLibraryResponse"][] } } } }; post: { requestBody: { content: { "application/json": components["schemas"]["VisualLibraryUpsertRequest"] } }; responses: { 201: { content: { "application/json": components["schemas"]["VisualLibraryResponse"] } } } } };
  "/api/library/items/{id}": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["VisualLibraryResponse"] } }; 404: { content?: never } } }; put: { parameters: { path: { id: string } }; requestBody: { content: { "application/json": components["schemas"]["VisualLibraryUpsertRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["VisualLibraryResponse"] } } } }; delete: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["ReferencedDeleteResponse"] } }; 409: { content: { "application/json": components["schemas"]["ReferencedDeleteResponse"] } } } } };
  "/api/library/assets": { get: { responses: { 200: { content: { "application/json": components["schemas"]["AssetLibraryResponse"][] } } } }; post: { responses: { 201: { content: { "application/json": components["schemas"]["AssetLibraryResponse"] } } } } };
  "/api/library/assets/{id}": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["AssetLibraryResponse"] } }; 404: { content?: never } } }; put: { parameters: { path: { id: string } }; requestBody: { content: { "application/json": components["schemas"]["AssetLibraryUpdateRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["AssetLibraryResponse"] } } } }; delete: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["ReferencedDeleteResponse"] } }; 409: { content: { "application/json": components["schemas"]["ReferencedDeleteResponse"] } } } } };
  "/api/library/assets/{id}/preview": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/octet-stream": unknown } }; 404: { content?: never } } } };
  "/api/projects/{projectId}/characters/states/": { get: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["ProjectCharacterStateResponse"][] } } } } };
  "/api/projects/{projectId}/characters/states/{characterId}": { put: { parameters: { path: { projectId: string; characterId: string } }; requestBody: { content: { "application/json": components["schemas"]["ProjectCharacterStateRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["ProjectCharacterStateResponse"] } } } } };

  "/api/providers/": { get: { responses: { 200: { content: { "application/json": components["schemas"]["ProviderCatalogResponse"][] } } } } };
  "/api/providers/{providerId}/settings": { get: { parameters: { path: { providerId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["ProviderSettingsResponse"] } }; 404: { content?: never } } }; put: { parameters: { path: { providerId: string } }; requestBody: { content: { "application/json": components["schemas"]["ProviderSettingsRequest"] } }; responses: { 200: { content: { "application/json": components["schemas"]["ProviderSettingsResponse"] } }; 400: { content?: unknown }; 404: { content?: never } } } };
  "/api/jobs/": { get: { responses: { 200: { content: { "application/json": components["schemas"]["JobResponse"][] } } } }; post: { requestBody: { content: { "application/json": components["schemas"]["JobCreateRequest"] } }; responses: { 201: { content: { "application/json": components["schemas"]["JobResponse"] } }; 400: { content?: unknown } } } };
  "/api/jobs/{id}": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["JobResponse"] } }; 404: { content?: never } } } };
  "/api/jobs/{id}/attempts": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": components["schemas"]["JobAttemptResponse"][] } }; 404: { content?: never } } } };
  "/api/jobs/{id}/dependencies": { get: { parameters: { path: { id: string } }; responses: { 200: { content: { "application/json": string[] } }; 404: { content?: never } } } };
  "/api/jobs/{id}/pause": JobActionPath; "/api/jobs/{id}/resume": JobActionPath; "/api/jobs/{id}/retry": JobActionPath; "/api/jobs/{id}/restart": JobActionPath; "/api/jobs/{id}/cancel": JobActionPath;
  "/api/jobs/projects/{projectId}/pause": JobProjectActionPath; "/api/jobs/projects/{projectId}/resume": JobProjectActionPath; "/api/jobs/projects/{projectId}/cancel": JobProjectActionPath;
  "/api/jobs/projects/{projectId}/scenes/{sceneId}/pause": JobSceneActionPath; "/api/jobs/projects/{projectId}/scenes/{sceneId}/resume": JobSceneActionPath; "/api/jobs/projects/{projectId}/scenes/{sceneId}/cancel": JobSceneActionPath;
  "/api/jobs/events": { get: { responses: { 200: { content: { "text/event-stream": string } } } } };
}

interface JobActionPath { post: { parameters: { path: { id: string } }; responses: { 200: { content?: unknown }; 404: { content?: never }; 409: { content?: never } } } }
interface JobProjectActionPath { post: { parameters: { path: { projectId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["JobScopeActionResponse"] } } } } }
interface JobSceneActionPath { post: { parameters: { path: { projectId: string; sceneId: string } }; responses: { 200: { content: { "application/json": components["schemas"]["JobScopeActionResponse"] } } } } }

export interface components {
  schemas: {
    SystemVersionResponse: { applicationName: string; version: string; environment: string };
    ProjectAspectRatio: "Landscape16x9" | "Portrait9x16" | "Square1x1";
    GenerationPreset: "Fast" | "Balanced" | "BestQuality" | "Cheapest" | "Custom";
    ProjectReferenceKind: "Song" | "Character" | "Style" | "Location" | "AdditionalMedia";
    ProjectReferenceRequest: { kind: components["schemas"]["ProjectReferenceKind"]; referenceId: string };
    ProjectUpsertRequest: { title: string; artist: string; lyrics: string; storyline: string; meaning: string; visualDirection: string; mood: string; genre: string; aspectRatio: components["schemas"]["ProjectAspectRatio"]; resolutionWidth: number; resolutionHeight: number; targetPlatforms?: string[] | null; preset: components["schemas"]["GenerationPreset"]; estimatedBudget?: number | null; maximumBudget?: number | null; references?: components["schemas"]["ProjectReferenceRequest"][] | null };
    ProjectReferenceResponse: { kind: components["schemas"]["ProjectReferenceKind"]; referenceId: string };
    ProjectResponse: { id: string; title: string; artist: string; lyrics: string; storyline: string; meaning: string; visualDirection: string; mood: string; genre: string; aspectRatio: components["schemas"]["ProjectAspectRatio"]; resolutionWidth: number; resolutionHeight: number; targetPlatforms: string[]; preset: components["schemas"]["GenerationPreset"]; estimatedBudget?: number | null; maximumBudget?: number | null; references: components["schemas"]["ProjectReferenceResponse"][]; createdUtc: string; updatedUtc: string };
    ProjectSongResponse: { assetId: string; mimeType: string; fileSize: number; checksumSha256: string; createdUtc: string };

    SongSectionKind: "Unknown" | "Intro" | "Verse" | "PreChorus" | "Chorus" | "Bridge" | "Breakdown" | "Instrumental" | "Outro";
    AnalysisValueSource: "Detected" | "UserEdited" | "Imported";
    WaveformBucketResponse: { startSeconds: number; endSeconds: number; minimum: number; maximum: number; rms: number };
    EnergyPointResponse: { timeSeconds: number; value: number };
    BeatMarkerResponse: { timeSeconds: number; confidence: number };
    BarMarkerResponse: { number: number; timeSeconds: number; confidence: number };
    PhraseMarkerResponse: { number: number; startSeconds: number; endSeconds: number; confidence: number };
    QuietRangeResponse: { startSeconds: number; endSeconds: number; averageEnergy: number };
    VocalActivityResponse: { vocalFraction: number; instrumentalFraction: number; confidence: number; method: string };
    SongSectionRequest: { id?: string | null; label: string; kind: components["schemas"]["SongSectionKind"]; startSeconds: number; endSeconds: number };
    SongSectionResponse: { id: string; label: string; kind: components["schemas"]["SongSectionKind"]; startSeconds: number; endSeconds: number; confidence: number; source: components["schemas"]["AnalysisValueSource"] };
    SongAnalysisResponse: { id: string; projectId: string; sourceAssetId: string; version: number; durationSeconds: number; bpm?: number | null; sampleRate?: number | null; channels?: number | null; codec?: string | null; bitRate?: number | null; waveform: components["schemas"]["WaveformBucketResponse"][]; energy: components["schemas"]["EnergyPointResponse"][]; beats: components["schemas"]["BeatMarkerResponse"][]; bars: components["schemas"]["BarMarkerResponse"][]; phrases: components["schemas"]["PhraseMarkerResponse"][]; quietRanges: components["schemas"]["QuietRangeResponse"][]; vocalActivity?: components["schemas"]["VocalActivityResponse"] | null; sections: components["schemas"]["SongSectionResponse"][]; createdUtc: string };
    TranscriptionSegmentRequest: { startSeconds: number; endSeconds: number; text: string };
    LyricTimingLineResponse: { lineNumber: number; text: string; startSeconds?: number | null; endSeconds?: number | null; confidence: number; isMatched: boolean };
    LyricTimingResponse: { id: string; projectId: string; sourceAssetId: string; songAnalysisId: string; version: number; suppliedLyricsSha256: string; matchedFraction: number; lines: components["schemas"]["LyricTimingLineResponse"][]; createdUtc: string };

    DirectorControls: { literalToSymbolic: number; narrativeStrength: number; abstraction: number; emotion: number; darkness: number; surrealism: number; complexity: number; actingIntensity: number; cameraEnergy: number };
    DirectorPlanRequest: { controls: components["schemas"]["DirectorControls"] };
    VisualArcPointRequest: { id?: string | null; timeSeconds: number; label: string; description: string; emotionalIntensity: number; visualIntensity: number; cameraEnergy: number };
    VisualArcPointResponse: { id: string; timeSeconds: number; label: string; description: string; emotionalIntensity: number; visualIntensity: number; cameraEnergy: number };
    VisualArcUpdateRequest: { summary: string; controls: components["schemas"]["DirectorControls"]; points?: components["schemas"]["VisualArcPointRequest"][] | null };
    VisualArcResponse: { id: string; projectId: string; songAnalysisId: string; version: number; summary: string; controls: components["schemas"]["DirectorControls"]; points: components["schemas"]["VisualArcPointResponse"][]; createdUtc: string };
    StoryboardSceneDetailsRequest: { songSection: string; associatedLyric: string; purpose: string; emotion: string; composition: string; lighting: string; environmentMotion: string; visualSymbolism: string; continuityRequirements: string };
    StoryboardSceneDetailsResponse: { songSection: string; associatedLyric: string; purpose: string; emotion: string; composition: string; lighting: string; environmentMotion: string; visualSymbolism: string; continuityRequirements: string };
    SceneUpdateRequest: { startSeconds: number; endSeconds: number; title: string; directorIntent: string; action: string; environment: string; camera: string; transitionIn: string; characterIds?: string[] | null; styleIds?: string[] | null; locationIds?: string[] | null; details?: components["schemas"]["StoryboardSceneDetailsRequest"] | null };
    SceneReorderRequest: { sceneIds?: string[] | null };
    StoryboardSceneResponse: { id: string; sequence: number; startSeconds: number; endSeconds: number; title: string; directorIntent: string; action: string; environment: string; camera: string; transitionIn: string; characterIds: string[]; styleIds: string[]; locationIds: string[]; selectedPromptVersionId?: string | null; details: components["schemas"]["StoryboardSceneDetailsResponse"] };
    StoryboardResponse: { id: string; projectId: string; songAnalysisId: string; visualArcId: string; version: number; scenes: components["schemas"]["StoryboardSceneResponse"][]; createdUtc: string };
    PromptRegenerateRequest: { notes?: string | null };
    PromptVersionResponse: { id: string; projectId: string; sceneId: string; storyboardVersionId: string; version: number; templateName: string; templateVersion: number; directorIntent: string; finalProviderPrompt: string; createdUtc: string };
    DirectorPlanResponse: { visualArc: components["schemas"]["VisualArcResponse"]; storyboard: components["schemas"]["StoryboardResponse"]; initialPrompts: components["schemas"]["PromptVersionResponse"][] };
    PromptRegenerateResponse: { storyboard: components["schemas"]["StoryboardResponse"]; prompt: components["schemas"]["PromptVersionResponse"] };

    VisualLibraryKind: "Character" | "Style" | "Location";
    CharacterReferenceType: "Photo" | "Turnaround" | "Illustration" | "ConceptArt" | "Other";
    CharacterContinuityLocks: { identity: boolean; face: boolean; hair: boolean; body: boolean; age: boolean; wardrobe: boolean };
    CharacterOutfit: { id: string; name: string; description: string; assetEntryIds: string[] };
    CharacterLibraryData: { referenceType: components["schemas"]["CharacterReferenceType"]; appearanceDescription: string; forbiddenChanges: string[]; outfits: components["schemas"]["CharacterOutfit"][]; defaultLocks: components["schemas"]["CharacterContinuityLocks"] };
    StyleLibraryData: { prompt: string; cameraCharacteristics: string; lightingCharacteristics: string; animationCharacteristics: string };
    LocationLibraryData: { environmentDescription: string; constraints: string[]; lighting: string; weather: string; timeOfDay: string };
    VisualLibraryUpsertRequest: { kind: components["schemas"]["VisualLibraryKind"]; name: string; description: string; tags?: string[] | null; isFavorite: boolean; assetEntryIds?: string[] | null; character?: components["schemas"]["CharacterLibraryData"] | null; style?: components["schemas"]["StyleLibraryData"] | null; location?: components["schemas"]["LocationLibraryData"] | null };
    VisualLibraryResponse: { id: string; kind: components["schemas"]["VisualLibraryKind"]; name: string; description: string; tags: string[]; isFavorite: boolean; assetEntryIds: string[]; character?: components["schemas"]["CharacterLibraryData"] | null; style?: components["schemas"]["StyleLibraryData"] | null; location?: components["schemas"]["LocationLibraryData"] | null; createdUtc: string; updatedUtc: string };
    AssetLibraryUpdateRequest: { name: string; tags?: string[] | null; isFavorite: boolean; sourceDescription?: string | null };
    AssetLibraryResponse: { id: string; mediaAssetId: string; previewMediaAssetId?: string | null; name: string; tags: string[]; isFavorite: boolean; sourceDescription: string; createdUtc: string; updatedUtc: string };
    ReferencedDeleteResponse: { deleted: boolean; referencingIds: string[] };
    ProjectCharacterStateRequest: { outfitId?: string | null; locks: components["schemas"]["CharacterContinuityLocks"]; stateValues?: Record<string, number> | null };
    ProjectCharacterStateResponse: { projectId: string; characterId: string; outfitId?: string | null; locks: components["schemas"]["CharacterContinuityLocks"]; stateValues: Record<string, number>; updatedUtc: string };

    ProviderCapability: "TextGeneration" | "ImageGeneration" | "ImageEditing" | "VideoGeneration" | "ImageToVideo" | "VideoToVideo" | "LipSync" | "Upscale" | "Transcription" | "VisionEvaluation" | "DirectorPlanning";
    CredentialReferenceKind: "Environment" | "OperatingSystem" | "External";
    CredentialReference: { kind: components["schemas"]["CredentialReferenceKind"]; identifier: string };
    ProviderModelResponse: { modelId: string; displayName: string; capabilities: components["schemas"]["ProviderCapability"][]; supportsReferences: boolean; supportsStartFrame: boolean; supportsEndFrame: boolean; supportsSeed: boolean; supportsNegativePrompt: boolean; supportsNativeAudio: boolean; maxReferences: number; supportedDurationsSeconds: number[]; supportedAspectRatios: string[]; supportedResolutions: string[] };
    ProviderSettingsResponse: { providerId: string; enabled: boolean; credentialReference?: components["schemas"]["CredentialReference"] | null; defaultModels: Partial<Record<components["schemas"]["ProviderCapability"], string>>; maxConcurrency: number; timeoutSeconds: number; maxRetries: number; allowedOperations: components["schemas"]["ProviderCapability"][]; priority: number; fallbackPriority: number };
    ProviderSettingsRequest: { enabled: boolean; credentialReference?: components["schemas"]["CredentialReference"] | null; defaultModels: Partial<Record<components["schemas"]["ProviderCapability"], string>>; maxConcurrency: number; timeoutSeconds: number; maxRetries: number; allowedOperations: components["schemas"]["ProviderCapability"][]; priority: number; fallbackPriority: number };
    ProviderCatalogResponse: { id: string; displayName: string; models: components["schemas"]["ProviderModelResponse"][]; settings: components["schemas"]["ProviderSettingsResponse"] };
    JobState: "Draft" | "Queued" | "Submitting" | "ProviderQueued" | "Generating" | "Downloading" | "Validating" | "Completed" | "Paused" | "WaitingForQuota" | "WaitingForProvider" | "WaitingForDependency" | "RetryScheduled" | "Rejected" | "FailedRetryable" | "FailedPermanent" | "Cancelled";
    JobCreateRequest: { projectId?: string | null; sceneId?: string | null; parentJobId?: string | null; type: string; payloadJson: string; providerId?: string | null; modelId?: string | null; priority: number; maxRetries: number; estimatedCost?: number | null; currency?: string | null; dependencies?: string[] | null };
    JobResponse: { id: string; projectId?: string | null; sceneId?: string | null; parentJobId?: string | null; type: string; providerId?: string | null; modelId?: string | null; state: components["schemas"]["JobState"]; resumeState?: components["schemas"]["JobState"] | null; priority: number; attemptCount: number; retryCount: number; maxRetries: number; createdUtc: string; updatedUtc: string; nextRunUtc?: string | null; startedUtc?: string | null; completedUtc?: string | null; providerTaskId?: string | null; errorCode?: string | null; errorMessage?: string | null; estimatedCost?: number | null; actualCost?: number | null; currency?: string | null };
    JobAttemptResponse: { attemptNumber: number; startedUtc: string; completedUtc?: string | null; state: components["schemas"]["JobState"]; providerTaskId?: string | null; errorCode?: string | null; errorMessage?: string | null; estimatedCost?: number | null; actualCost?: number | null; currency?: string | null };
    JobScopeActionResponse: { affectedJobs: number };
  };
}
